name: Chocolatey Package Auto Update

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  update_packages:
    runs-on: windows-latest

    strategy:
      matrix:
        package:
          - Bitwig
          - DMGAudio\Compassion
          - DMGAudio\Dualism
          - DMGAudio\EQuality
          - DMGAudio\EQuick
          - DMGAudio\EQuilibrium
          - DMGAudio\Essence
          - DMGAudio\Expurgate
          - DMGAudio\Limitless
          - DMGAudio\Multiplicity
          - DMGAudio\PitchFunk
          - DMGAudio\TrackComp
          - DMGAudio\TrackControl
          - DMGAudio\TrackDS
          - DMGAudio\TrackGate
          - DMGAudio\TrackLimit
          - DMGAudio\TrackMeter
          - FabFilter\Micro (x64)
          - FabFilter\Micro (x86)
          - FabFilter\One (x64)
          - FabFilter\One (x86)
          - FabFilter\Pro-C 2 (x64)
          - FabFilter\Pro-C 2 (x86)
          - FabFilter\Pro-DS (x64)
          - FabFilter\Pro-DS (x86)
          - FabFilter\Pro-G (x64)
          - FabFilter\Pro-G (x86)
          - FabFilter\Pro-L (x64)
          - FabFilter\Pro-L (x86)
          - FabFilter\Pro-L 2 (x64)
          - FabFilter\Pro-L 2 (x86)
          - FabFilter\Pro-MB (x64)
          - FabFilter\Pro-MB (x86)
          - FabFilter\Pro-Q 2 (x64)
          - FabFilter\Pro-Q 2 (x86)
          - FabFilter\Pro-Q 3 (x64)
          - FabFilter\Pro-Q 3 (x86)
          - FabFilter\Pro-Q 4 (x64)
          - FabFilter\Pro-Q 4 (x86)
          - FabFilter\Pro-R (x64)
          - FabFilter\Pro-R (x86)
          - FabFilter\Pro-R 2 (x64)
          - FabFilter\Pro-R 2 (x86)
          - FabFilter\Saturn (x64)
          - FabFilter\Saturn (x86)
          - FabFilter\Saturn 2 (x64)
          - FabFilter\Saturn 2 (x86)
          - FabFilter\Simplon (x64)
          - FabFilter\Simplon (x86)
          - FabFilter\Timeless 2 (x64)
          - FabFilter\Timeless 2 (x86)
          - FabFilter\Timeless 3 (x64)
          - FabFilter\Timeless 3 (x86)
          - FabFilter\Total Bundle (x64)
          - FabFilter\Total Bundle (x86)
          - FabFilter\Twin 2 (x64)
          - FabFilter\Twin 2 (x86)
          - FabFilter\Twin 3 (x64)
          - FabFilter\Twin 3 (x86)
          - FabFilter\Volcano 2 (x64)
          - FabFilter\Volcano 2 (x86)
          - FabFilter\Volcano 3 (x64)
          - FabFilter\Volcano 3 (x86)
          - MadronaLabs\Aalto
          - MadronaLabs\Aaltoverb
          - MadronaLabs\Kaivo
          - MadronaLabs\Sumu
          - MadronaLabs\Virta
          - Voxengo\AnSpec
          - Voxengo\Beeper
          - Voxengo\BMS
          - Voxengo\Boogex
          - Voxengo\Correlometer
          - Voxengo\CRTIV Tape Bus
          - Voxengo\Crunchessor
          - Voxengo\CurveEQ
          - Voxengo\Deft Compressor
          - Voxengo\Drumformer
          - Voxengo\EBusLim
          - Voxengo\Elephant
          - Voxengo\GlissEQ
          - Voxengo\HarmoniEQ
          - Voxengo\Latency Delay
          - Voxengo\LF Max Punch
          - Voxengo\Marquis Compressor
          - Voxengo\Marvel GEQ
          - Voxengo\MSED
          - Voxengo\OldSkoolVerb
          - Voxengo\OldSkoolVerb Plus
          - Voxengo\OVC-128
          - Voxengo\Overtone GEQ
          - Voxengo\Peakbuster
          - Voxengo\PHA-979
          - Voxengo\Polysquasher 3
          - Voxengo\Powershaper
          - Voxengo\PrimeEQ
          - Voxengo\r8brain PRO
          - Voxengo\Shinechilla
          - Voxengo\Shumovick
          - Voxengo\Sobor
          - Voxengo\Soniformer
          - Voxengo\Sound Delay
          - Voxengo\SPAN
          - Voxengo\SPAN Plus
          - Voxengo\Spatifier
          - Voxengo\Stereo Touch
          - Voxengo\Tempo Delay
          - Voxengo\TEOTE
          - Voxengo\TEQ-421
          - Voxengo\TransGainer
          - Voxengo\Tube Amp
          - Voxengo\VariSaturator
          - Voxengo\Voxformer
          - Voxengo\Warmifier
          - Voxengo\Water Chorus
      # max-parallel: 1

    steps:
      - uses: actions/checkout@v4
        with:
          ref: master

      - name: Install Chocolatey Automatic Package Updater Module
        run: Install-Module -Name Chocolatey-AU -Force

      - name: Run ${{ matrix.package }} update script
        id: update
        run: |
          cd "${{ matrix.package }}"
          $UpdateOutput = .\update.ps1
          $NupkgPath = (($UpdateOutput.Result | Where-Object {$_ -like '*.nupkg''*'}) -split "'")[1]
          Write-Output "NupkgPath=$($NupkgPath)" >> $Env:GITHUB_OUTPUT
          $UpdateStatus = if ($UpdateOutput.Result -match 'No new version found') {'No Update'} else {'Update Available'}
          Write-Output "UpdateStatus=$($UpdateStatus)" >> $Env:GITHUB_OUTPUT

      - name: Test ${{ matrix.package }} install and uninstall
        run: Test-Package -Install -Uninstall -Nu "${{ steps.update.outputs.NupkgPath }}"
        if: steps.update.outputs.UpdateStatus == 'Update Available' && !startsWith(matrix.package, 'FabFilter')

      - name: Test ${{ matrix.package }} install only (FabFilter uninstall requires manual interaction)
        run: Test-Package -Install -Nu "${{ steps.update.outputs.NupkgPath }}"
        if: steps.update.outputs.UpdateStatus == 'Update Available' && startsWith(matrix.package, 'FabFilter')

      - name: Publish to Chocolatey community feed
        run: |
          $Nupkg = '${{ steps.update.outputs.NupkgPath }}'
          $ApiKey = '${{ secrets.CHOCO_KEY }}'
          $ChocoServer = 'https://push.chocolatey.org/'
          choco push $Nupkg --source $ChocoServer --key $ApiKey
        if: steps.update.outputs.UpdateStatus == 'Update Available'

      - name: Pull Remote Changes
        run: git pull
        if: steps.update.outputs.UpdateStatus == 'Update Available'

      # - name: Commit Updated nuspec
      #   uses: stefanzweifel/git-auto-commit-action@v5
      #   with:
      #     commit_message: Apply Choco package update - ${{ matrix.package }} ${{ steps.update.outputs.newversion }}
      #     file_pattern: '*.nuspec *.ps1'
      #   if: steps.update.outputs.UpdateStatus == 'Update Available'
      - name: Commit Updated nuspec
        uses: EndBug/add-and-commit@v7
        with:
          message: Apply Choco package update - ${{ matrix.package }} ${{ steps.update.outputs.newversion }}
          pull_strategy: 'NO-PULL'
          push: false
        if: steps.update.outputs.UpdateStatus == 'Update Available'

      - name: Push changes with retry
        shell: pwsh
        if: steps.update.outputs.UpdateStatus == 'Update Available'
        run: |
          $maxAttempts = 5
          $attempt = 1
          do {
            Write-Host "Attempt ${attempt}: Pulling latest changes..."
            git pull --rebase
            Write-Host "Attempt ${attempt}: Pushing commit..."
            git push
            if ($LASTEXITCODE -eq 0) {
                Write-Host "Push succeeded on attempt ${attempt}."
                break
            }
            Write-Host "Push failed on attempt ${attempt}. Retrying in 10 seconds..."
            Start-Sleep -Seconds 10
            $attempt++
          } while ($attempt -le $maxAttempts)
          if ($LASTEXITCODE -ne 0) {
              Write-Error "Push failed after ${maxAttempts} attempts."
              exit 1
          }
